---
- hosts: network
  tasks:
  - name: Check OVS ID for ONOS
    become: yes
    shell: "sudo ovs-ofctl show {{ item.name }} | grep -oEi 'dpid(.*)' | awk '{split($0,array,\":\"); print \"of:\" array[2]}'"
    loop: "{{ hostvars[inventory_hostname]['ovs'] }}"
    when: item.controller is defined
    register: switchid
  - name: Parse switchid array
    set_fact:
      switcharray: "{{ hostvars | community.general.json_query('*.switchid.results[*].stdout') }}"
  - name: Initiate dictionaries
    set_fact:
      switchdict: {}
      portdict: {}
  - name: Add switches into switch dict
    set_fact:
      switchdict: "{{ switchdict | ansible.builtin.combine({hostvars[inventory_hostname]['ovs'][index]['name']: item}) }}"
    loop: "{{ switcharray[0] }}"
    loop_control:
      index_var: index
  - name: Get Port ID for ONOS
    become: yes
    shell: "sudo ovs-ofctl show {{ item.switchname }} | grep -oEi '(.)\\({{ item.portname }}\\)' | awk '{split($0,array,\"\\\\({{ item.portname }}\\\\)\"); print array[1]}'"
    loop: "{{ hostvars[inventory_hostname]['interfaces'] }}"
    register: portid
  - name: Parse portid array
    set_fact:
      portarray: "{{ hostvars | community.general.json_query('*.portid.results[*].stdout') }}"
  - name: Add ports into port dict
    set_fact:
      portdict: "{{ portdict | ansible.builtin.combine({hostvars[inventory_hostname]['interfaces'][index]['portname']: item}) }}"
    loop: "{{ portarray[0] }}"
    loop_control:
      index_var: index
  - name: Add temp host
    ansible.builtin.add_host:
      groups: temp
      name: 10.100.10.30

- hosts: temp
  gather_facts: no
  tasks:
    - name: Remove Interface
      ansible.builtin.shell:
        chdir: ~/fyp/
        cmd: "./removeInterface.exp {{ switchdict[item.switchname] }}/{{ portdict[item.portname] }} {{ item.portname }}"
      loop: "{{ hostvars[inventory_hostname]['interfaces'] }}"
    - name: Remove BGP Speaker
      ansible.builtin.shell:
        chdir: ~/fyp/
        cmd: "./removeBGPSpeaker.exp {{ hostvars[inventory_hostname]['bgpspeaker'][0]['portname'] }}"
...
