---
- hosts: network
  tasks:
  - name: Display
    debug:
      msg: "--key {{ item.node }}-{{ item.sourceNet }}-{{ item.destNet }}-{{ item.ethertype }}"
    loop: "{{ hostvars[inventory_hostname]['intents'] }}"
...
